#!/usr/bin/env bash

case "${1:-}" in
	get)
		echo 1
		;;

	stop)
		cat <<- END
			Recorded tag
			  Started 2022-01-25T21:00:09
			  Ended                 07:24
			  Total               0:07:15
		END
		;;

	*)
		echo "${*}" >&2
		;;
esac
