#!/usr/bin/env bash
set -eu -o pipefail
shopt -u expand_aliases
IFS=$'\n\t'

if [[ "${1:-}" == '--help' ]]; then
	cat <<- END
	NAME
	       timew-cut - stop tracking and truncate the stopped interval to the closest minute

	SYNOPSIS
	       timew cut [<date>] [<tag>...]

	DESCRIPTION
	       Acts exactly like timew-stop, with the addition that the stopped interval is automatically
	       shortened so its duration in minutes is an integer.

	       This allows for a more precise tally of short, repeated intervals that have the same tags.

	SEE ALSO
	       timew-stop, timew-cancel
	END
	exit 0
fi

toki stop "${@}" >/dev/null

if [[ "$(timew get dom.tracked.1.duration || true)" =~ M([0-9]+)S$ ]]; then
	timew shorten @1 "${BASH_REMATCH[1]}seconds" >/dev/null
fi
